Repository Nixtla/neuralforecast, pull requests merged in 2024-05, with the labels that each got.

#989 fix cross_validation results with uneven windows
  .github/workflows/ci.yaml
  nbs/core.ipynb
  nbs/models.bitcn.ipynb
  nbs/models.hint.ipynb
  neuralforecast/core.py
Labels: fix

#971 [FEAT] TiDE model
  action_files/test_models/src/evaluation.py
  action_files/test_models/src/models.py
  nbs/core.ipynb
  nbs/imgs_models/tide.png
  nbs/models.ipynb
  nbs/models.tide.ipynb
  neuralforecast/_modidx.py
  neuralforecast/auto.py
  neuralforecast/core.py
  neuralforecast/models/__init__.py
  neuralforecast/models/tide.py
Labels: feature

#991 [FIX] Refit after validation boolean
  nbs/common.base_auto.ipynb
  neuralforecast/common/_base_auto.py
Labels: fix

#946 Update models in the README
  README.md
Labels: documentation

#978 fix: add tsmixer tutorial to sidebar
  nbs/mint.json
Labels: documentation
