Repository Nixtla/neuralforecast, pull requests merged in 2024-01, with the labels that each got.

#844 copy config in optuna
  nbs/common.base_auto.ipynb
  neuralforecast/common/_base_auto.py
Labels: fix

#849 use future instead of deprecation warnings
  environment.yml
  nbs/core.ipynb
  nbs/tsdataset.ipynb
  neuralforecast/core.py
  neuralforecast/tsdataset.py
  settings.ini
Labels: enhancement

#850 fix save with save_dataset=False
  nbs/core.ipynb
  neuralforecast/core.py
Labels: fix

#851 ensure exogenous features are lists
  nbs/common.base_multivariate.ipynb
  nbs/common.base_recurrent.ipynb
  nbs/common.base_windows.ipynb
  neuralforecast/common/_base_multivariate.py
  neuralforecast/common/_base_recurrent.py
  neuralforecast/common/_base_windows.py
Labels: fix

#862 [FIX] Polars `.columns` produces list rather than Pandas Index
  nbs/tsdataset.ipynb
  neuralforecast/tsdataset.py
Labels: fix

#867 support saving and loading models with alias
  nbs/core.ipynb
  neuralforecast/core.py
Labels: fix

#871 switch `flake8` to `ruff`
  .github/workflows/lint.yaml
  .mypy.ini
  CONTRIBUTING.md
  pyproject.toml
  settings.ini
Labels: enhancement

#873 use scalers from coreforecast
  environment.yml
  nbs/core.ipynb
  neuralforecast/core.py
  settings.ini
Labels: dependencies

#882 chore: update license to apache-2
  LICENSE
Labels: documentation
