Repository Nixtla/neuralforecast, pull requests merged in 2024-04, with the labels that each got.

#951 fix cross_validation when the id is the index
  nbs/core.ipynb
  neuralforecast/core.py
Labels: fix

#944 [FEAT] - Add iTransformer to neuralforecast
  nbs/core.ipynb
  nbs/imgs_models/iTransformer.png
  nbs/models.ipynb
  nbs/models.itransformer.ipynb
  neuralforecast/_modidx.py
  neuralforecast/auto.py
  neuralforecast/core.py
  neuralforecast/models/__init__.py
  neuralforecast/models/itransformer.py
Labels: feature

#953 fix early stopping in ray auto models
  nbs/common.base_model.ipynb
  nbs/common.base_multivariate.ipynb
  nbs/common.base_recurrent.ipynb
  nbs/common.base_windows.ipynb
  neuralforecast/common/_base_model.py
  neuralforecast/common/_base_multivariate.py
  neuralforecast/common/_base_recurrent.py
  neuralforecast/common/_base_windows.py
Labels: fix

#959 handle exogenous variables of TFT in parent class
  environment-cpu.yml
  nbs/models.tft.ipynb
  neuralforecast/models/tft.py
Labels: fix

#964 [FIX] HINT not producing coherent forecasts
  nbs/models.hint.ipynb
  neuralforecast/models/hint.py
Labels: fix

#961 [FIX] Fixes default settings of BiTCN
  nbs/models.bitcn.ipynb
  neuralforecast/models/bitcn.py
Labels: fix

#966 [FIX] raise_exception_nbeats_h=1_with_stacks
  nbs/models.nbeats.ipynb
  neuralforecast/models/nbeats.py
Labels: fix

#967 [FIX] fix_wrong_import_doc PatchTST
  nbs/models.patchtst.ipynb
Labels: fix

#974 reduce default warnings
  nbs/common.base_model.ipynb
  nbs/common.base_multivariate.ipynb
  nbs/common.base_recurrent.ipynb
  nbs/common.base_windows.ipynb
  nbs/core.ipynb
  nbs/models.bitcn.ipynb
  nbs/models.deepar.ipynb
  nbs/models.ipynb
  nbs/models.itransformer.ipynb
  nbs/tsdataset.ipynb
  neuralforecast/_modidx.py
  neuralforecast/common/_base_model.py
  neuralforecast/common/_base_multivariate.py
  neuralforecast/common/_base_recurrent.py
  neuralforecast/common/_base_windows.py
  neuralforecast/core.py
  neuralforecast/models/deepar.py
  neuralforecast/tsdataset.py
Labels: enhancement
