Repository Nixtla/neuralforecast, pull requests merged in 2024-07, with the labels that each got.

#1031 automatically set refit_with_val when early stopping is enabled
  nbs/common.base_auto.ipynb
  nbs/core.ipynb
  neuralforecast/common/_base_auto.py
Labels: enhancement

#1033 update min_size in TimeSeriesDataset.append
  nbs/tsdataset.ipynb
  neuralforecast/tsdataset.py
Labels: fix

#1034 suppress warning when saving hyperparameters in base auto
  nbs/common.base_auto.ipynb
  neuralforecast/common/_base_auto.py
Labels: enhancement

#1066 use commit hash in actions and add dependabot updates
  .github/dependabot.yml
  .github/workflows/build-docs.yaml
  .github/workflows/ci.yaml
  .github/workflows/lint.yaml
  .github/workflows/no-response.yaml
  .github/workflows/python-publish.yml
  .github/workflows/release-drafter.yml
Labels: dependencies

#1074 [DOCS] add tutorial for large dataset DataLoader
  nbs/examples/Large_Datasets_Tutorial.ipynb
  nbs/mint.json
  nbs/sidebar.yml
Labels: documentation

#1055 [FEAT[ - Add multivariate evaluation to CI
  .circleci/config.yml
  action_files/test_models/src/data.py
  action_files/test_models/src/multivariate_evaluation.py
  action_files/test_models/src/multivariate_models.py
Labels: feature

#1071 [FEAT] - Add TimeMixer
  action_files/test_models/src/multivariate_evaluation.py
  action_files/test_models/src/multivariate_models.py
  nbs/common.modules.ipynb
  nbs/core.ipynb
  nbs/imgs_models/timemixer.png
  nbs/models.autoformer.ipynb
  nbs/models.ipynb
  nbs/models.timemixer.ipynb
  neuralforecast/_modidx.py
  neuralforecast/auto.py
  neuralforecast/common/_modules.py
  neuralforecast/core.py
  neuralforecast/models/__init__.py
  neuralforecast/models/autoformer.py
  neuralforecast/models/timemixer.py
Labels: feature

#1063 [DOCS] Restructure documentation
  README.md
  nbs/_quarto.yml
  nbs/custom.yml
  nbs/docs/api-reference/.notest
  nbs/docs/api-reference/01_neuralforecast_map.ipynb
  nbs/docs/capabilities/.notest
  nbs/docs/capabilities/01_overview.qmd
  nbs/docs/capabilities/02_objectives.qmd
  nbs/docs/capabilities/03_exogenous_variables.ipynb
  nbs/docs/capabilities/04_hyperparameter_tuning.ipynb
  nbs/docs/capabilities/05_predictInsample.ipynb
  nbs/docs/capabilities/06_save_load_models.ipynb
  nbs/docs/capabilities/07_time_series_scaling.ipynb
  nbs/docs/getting-started/.notest
  nbs/docs/getting-started/01_introduction.ipynb
  nbs/docs/getting-started/02_quickstart.ipynb
  nbs/docs/getting-started/04_installation.ipynb
  nbs/docs/getting-started/05_datarequirements.ipynb
  nbs/docs/tutorials/.notest
  nbs/docs/tutorials/01_getting_started_complete.ipynb
  nbs/docs/tutorials/02_cross_validation.ipynb
  nbs/docs/tutorials/03_uncertainty_quantification.ipynb
  nbs/docs/tutorials/04_longhorizon_nhits.ipynb
  nbs/docs/tutorials/05_longhorizon_transformers.ipynb
  nbs/docs/tutorials/06_longhorizon_probabilistic.ipynb
  nbs/docs/tutorials/07_forecasting_tft.ipynb
  nbs/docs/tutorials/08_multivariate_tsmixer.ipynb
  nbs/docs/tutorials/09_hierarchical_forecasting.ipynb
  nbs/docs/tutorials/10_distributed_neuralforecast.ipynb
  nbs/docs/tutorials/11_intermittent_data.ipynb
  nbs/docs/tutorials/12_using_mlflow.ipynb
  nbs/docs/tutorials/13_robust_forecasting.ipynb
  nbs/docs/tutorials/14_interpretable_decompositions.ipynb
  nbs/docs/tutorials/16_temporal_classification.ipynb
  nbs/docs/tutorials/17_transfer_learning.ipynb
  nbs/docs/tutorials/18_adding_models.ipynb
  nbs/docs/tutorials/19_large_datasets.ipynb
  nbs/docs/use-cases/.notest
  nbs/docs/use-cases/electricity_peak_forecasting.ipynb
  nbs/docs/use-cases/predictive_maintenance.ipynb
  nbs/examples/Exogenous_Variables.ipynb
  nbs/examples/models_intro.qmd
  nbs/mint.json
  nbs/models.ipynb
  nbs/sidebar.yml
Labels: documentation

#1081 [FIX] ignore pytorch lightning's PossibleUserWarning
  nbs/core.ipynb
  neuralforecast/core.py
Labels: fix

#999 Feature/kan experiment
  action_files/test_models/src/evaluation.py
  action_files/test_models/src/models.py
  experiments/kan_benchmark/README.md
  experiments/kan_benchmark/environment.yml
  experiments/kan_benchmark/run_experiment.py
  nbs/core.ipynb
  nbs/models.ipynb
  nbs/models.kan.ipynb
  neuralforecast/_modidx.py
  neuralforecast/auto.py
  neuralforecast/core.py
  neuralforecast/models/__init__.py
  neuralforecast/models/kan.py
Labels: feature
